// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpSHKxQ15Zh-_Le43fjUZm-qt8zwfdF20',
    appId: '1:205487406272:web:81f7f3becc7506aa9f4125',
    messagingSenderId: '205487406272',
    projectId: 'loadserv-task',
    authDomain: 'loadserv-task.firebaseapp.com',
    storageBucket: 'loadserv-task.firebasestorage.app',
    measurementId: 'G-MCG74P932S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChhOx78PGxyPwjX4PNH_fOpxD6CsSBlhc',
    appId: '1:205487406272:android:64f7495c466623339f4125',
    messagingSenderId: '205487406272',
    projectId: 'loadserv-task',
    storageBucket: 'loadserv-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEUtP0qvuWauxSjLk1TxS736uEyYUdCN0',
    appId: '1:205487406272:ios:2083a9aaaebeff1e9f4125',
    messagingSenderId: '205487406272',
    projectId: 'loadserv-task',
    storageBucket: 'loadserv-task.firebasestorage.app',
    iosBundleId: 'com.example.loadservTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEUtP0qvuWauxSjLk1TxS736uEyYUdCN0',
    appId: '1:205487406272:ios:2083a9aaaebeff1e9f4125',
    messagingSenderId: '205487406272',
    projectId: 'loadserv-task',
    storageBucket: 'loadserv-task.firebasestorage.app',
    iosBundleId: 'com.example.loadservTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSHKxQ15Zh-_Le43fjUZm-qt8zwfdF20',
    appId: '1:205487406272:web:1842d32d7aec91c69f4125',
    messagingSenderId: '205487406272',
    projectId: 'loadserv-task',
    authDomain: 'loadserv-task.firebaseapp.com',
    storageBucket: 'loadserv-task.firebasestorage.app',
    measurementId: 'G-D9MLVZYPRV',
  );
}
